server:
  port: 8762
  servlet:
    context-path: /quartz

spring:
  application:
    name: task
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hello_test?userUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123123
  freemarker:
    template-loader-path: classpath:/templates/
    charset: UTF-8
    suffix: .html
    check-template-location: true
    content-type: text/html
    cache: false

mybatis:
  mapper-locations: classpath:/mapper/**.xml
  type-aliases-package: top.cg0509.task.entity


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false